<<Documentation
Name:- Anand Arvind Kulkarni
Date:- 07/10/2021
Description:- Program to read 'n' and generate pattern of number increasing top to bottom.
Sample i/p(1):-Enter the number : 4
Sample o/p(1):- 1
		2 3 
		4 5 6 
		7 8 9 10
Sample i/p(2):- Enter the number: 34
Sample o/p(2):- ERROR: Number out of range.Please enter the number between valid range 2<number<32"
Sample i/p(3):- Enter the number: 3c
Sample o/p(3):- 3c is not a number.Please enter a valid number.
Documentation

#!/bin/bash
#to print to pattern using for loop along with validation

read -p "Enter the  number: " number                 #input from the user
if [[ "$number" =~ ^[0-9]+$ ]]                       #validation to check the input is alphanumeric or numeric 
then
    if [ "$number" -le 2 -o "$number" -ge 32 ]       #To check the input is in a vaid range or not.
    then
	echo "ERROR: $number is out of range.Please enter the number between valid range 2<number<32" #error if out of range.
    else
	count=1                                      #initialised variable with value 1 & later increment the number in pattern 
	for rows in `seq $number`                    #variable assigned for no. of rows & for loop sequence based on the input number.
	do                              
	    for column in `seq $rows`                #The no. of columns will follow the no. of rows by for loop sequence iteration.
	    do  
		echo -n "$((count++)) "              #initial count=1 is incremented in the pattern generated by above for loop.
	    done                                    
	    echo                                                               
	done
    fi
else
    echo "Error: $number is not a number.Please enter a valid number"   #if the input is aplhanumeric than this error is shown.
fi


